export const INIT = 'INIT'

export const GET_USER_META = 'GET_USER_META'
export const SET_USER_META = 'SET_USER_META'

export const GET_NAVIGATION = 'GET_NAVIGATION'
export const SET_NAVIGATION = 'SET_NAVIGATION'
export const ADD_WORKSPACE_TO_NAVIGATION = 'ADD_WORKSPACE_TO_NAVIGATION'
export const SET_WORKSPACE = "SET_WORKSPACE"

