export const ALL_LISTS = "ALL_LISTS"
export const GET_LIST = "GET_LIST"
export const GET_LIST_SELECT_ITEMS = "GET_LIST_SELECT_ITEMS"
export const VUEX_SET_LIST = 'VUEX_SET_LIST'

export const SET_LIST = "SET_LIST"
export const FETCH_ALL_LISTS = "FETCH_ALL_LISTS"
export const FETCH_LISTS_WITH_DATA_BULK = "FETCH_LISTS_WITH_DATA_BULK"
